import type { Metadata } from "next";
import "./globals.css";
import HamburgerMenu from "./components/HamburgerMenu";
import { ClerkProvider, SignedOut, SignInButton, UserButton, SignedIn,} from "@clerk/nextjs";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body >
        <header > 
        
        </header>
        <main className="animate-easeIn">
           {children}
            
        </main>
      </body>
    </html>
  </ClerkProvider>  );
}
